# Generated by Django 4.0.6 on 2022-07-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=80)),
                ('designation', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
