# Generated by Django 4.0.6 on 2022-09-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usaz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ID', models.CharField(max_length=10)),
                ('user_name', models.CharField(max_length=20)),
                ('sign_in_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
