# Generated by Django 4.0.6 on 2022-07-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=80)),
                ('symptoms', models.CharField(max_length=200)),
                ('diagnosis', models.CharField(max_length=200)),
                ('time_of_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
